### ISSUE TITLE
Cannot install Rasa with Python 3.10: absl-py gives error "Python version 2.7 or 3.4+ is required"

### ISSUE THREAD

**Issue by rayjolt** [RasaHQ/rasa#11632]
### Rasa Open Source version

3.2.10

### Python version

Other

### What operating system are you using?

Linux

### What happened?

Python version: 3.10
(The version dropdown is broken, so I am inputting this manually.)

I tried to install Python the latest Rasa version With Python 3.10.7, but it failed when installing the absl-py package, with the error "Python version 2.7 or 3.4+ is required".

### Command / Request

```shell
python -m venv venv
source venv/bin/activate
pip install rasa
```

### Relevant log output

```shell
Collecting rasa
  Downloading rasa-1.10.2-py3-none-any.whl (510 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.3/510.3 kB 4.1 MB/s eta 0:00:00
Collecting webexteamssdk<1.4.0,>=1.1.1
  Downloading webexteamssdk-1.3.tar.gz (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting fbmessenger<6.1.0,>=6.0.0
  Downloading fbmessenger-6.0.0-py2.py3-none-any.whl (11 kB)
Collecting sklearn-crfsuite<0.4,>=0.3
  Downloading sklearn_crfsuite-0.3.6-py2.py3-none-any.whl (12 kB)
Collecting prompt-toolkit<3.0,>=2.0
  Downloading prompt_toolkit-2.0.10-py3-none-any.whl (340 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 340.0/340.0 kB 8.2 MB/s eta 0:00:00
Collecting twilio<6.27,>=6.26
  Downloading twilio-6.26.3-py2.py3-none-any.whl (979 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 979.1/979.1 kB 15.4 MB/s eta 0:00:00
Collecting sanic-cors<0.11.0,>=0.10.0b1
  Downloading Sanic_Cors-0.10.0.post3-py2.py3-none-any.whl (17 kB)
Collecting rocketchat_API<1.4.0,>=0.6.31
  Downloading rocketchat_API-1.3.1-py3-none-any.whl (9.6 kB)
Collecting slackclient<3.0.0,>=2.0.0
  Downloading slackclient-2.9.4-py2.py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 kB 2.8 MB/s eta 0:00:00
Collecting requests<3.0,>=2.23
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 1.8 MB/s eta 0:00:00
Collecting sanic-jwt<1.5.0,>=1.3.2
  Downloading sanic-jwt-1.4.1.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting tensorflow-estimator==2.1.0
  Downloading tensorflow_estimator-2.1.0-py2.py3-none-any.whl (448 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.0/449.0 kB 4.7 MB/s eta 0:00:00
Collecting pymongo[srv,tls]<3.9.0,>=3.8.0
  Downloading pymongo-3.8.0.tar.gz (649 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 649.9/649.9 kB 13.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting oauth2client==4.1.3
  Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 1.8 MB/s eta 0:00:00
Collecting kafka-python<2.0,>=1.4
  Downloading kafka_python-1.4.7-py2.py3-none-any.whl (266 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 266.1/266.1 kB 8.8 MB/s eta 0:00:00
Collecting pydot<1.5,>=1.4
  Downloading pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Collecting python-engineio<3.13,>=3.11
  Downloading python_engineio-3.12.1-py2.py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 1.7 MB/s eta 0:00:00
Collecting absl-py<0.10,>=0.9
  Downloading absl-py-0.9.0.tar.gz (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.0/104.0 kB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4i0j4vq9/absl-py_a6eb2966754f41d392d770f4e258b343/setup.py", line 34, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by rayjolt** [comment]
This is due to [abseil-py#161](https://github.com/abseil/abseil-py/issues/161), which was fixed in version 0.12.0.

**Comment by rayjolt** [comment]
I see - thanks for the clarification. I wonder if an easier-to-understand error message could be displayed when trying to pip install from 3.10? If someone sees the message "3.4+ is required" when they are using 3.10, it is going to be confusing.

**Comment by rnaimi** [comment]
agree... confusing message "3.4+ is required" but it should say 3.4-3.10 is required"... wasted an hour trying to figure out why it's not installing :(

**Comment by siddheshsonawane07** [comment]
any fix on this bug, tried installing rasa with python 3.11
dont want to downgrade the python version
any fix ?

**Comment by abdulwahab-aka-proton** [comment]
Using python 3.8 and still getting this error... 

EDIT:  This instruction from rasa forum seems to have done the trick.

![Image](https://github.com/user-attachments/assets/a0a5b4eb-8957-491b-94cc-7fefb5f23f0f)
