### ISSUE TITLE
Dynamic configuration of NLU endpoint (Tracker Aware Interpreter)

### ISSUE THREAD

**Issue by alexissmirnov** [RasaHQ/rasa#3015]
**Enhancement proposal**:
The interpreter invokes the NLU service to parse each message. The service endpoint URL is configurable via a configuration file and cannot be dynamically changed at runtime. The NLU endpoint receives the text of the message but doesn't receive the representation of the conversation.

The proposal is to allow the support of the following conceptual use cases:
1. *Greeting in the right language*
- The user signs up to a chat app, specifies their communication preferences (eg. English or French)
- Rasa utters the message "Hello!" or "Bonjour!" depending on the communication preference

2. *Language-specific NLU parsing*
- The user signs up to a chat app, specifies their communication preferences (eg. English or French)
- The user starts the chat by sending a message in a language of their choice
- Rasa utters the response in the same language

3. *Multi-language interaction*
- The user starts the chat in French
- Responses are in French
- The user sends a message in English
- Rasa sends the response to English

4. *Co-reference resolution*
Restaurant reservation chatbot
Rasa: How many people joining you for dinner?
User: Just one
Rasa: Ok, what is your meal preference?
User: Vegetarian
Rasa: Great choice, what about the other party?
User: Same as me
Rasa: Ok, confirmed. Party 1: vegetarian; Party 2: vegetarian

The task here is to determine that the message "Same as me" refers to the previous message.

**Proposed solution**
- Enhance the interpreter to have access to the tracker.
- Enhance the NLU configuration to specify the slot name that will contain the URL of the NLU service endpoint
- Enhance `parse` API of the NLU service to accept tracker state as input

**Comment by alexissmirnov** [comment]
There's additional benefit from the first approach. The interpreter can pass the tracker state all the way into the NLU service. This way, other use-cases are unlocked such as co-reference resolution, using slots as features in the NLU model, etc.

To do so, the rasa_nlu `/parse` method would have to be enhanced to take the tracker state.

The second option @lgrinberg may satisfy some of the use-cases, but more limiting.

If there's interest in a general-purpose implementation of the dynamic configuration of the NLU endpoint (eg. the use-cases of handling two languages) here's how that could be done:
- The `nlu` endpoints configuration specifies a slot name that stores the language value (eg. `endpoint_slot_name: my_user_language_preference`
- The `nlu` configuration maps the value of the language to the domain name eg `fr -> http://frech.my-nlu.com` 
In `TrackerAwareRasaNLUHttpInterpreter` class, we'd look at the configuration, get the value of the slot `my_user_language_preference` (it would be `fr`), then get the URL to the rasa_nlu service `http://frech.my-nlu.com`and use that send the `/parse` request.

**Comment by tmbo** [comment]
i think @amn41 has been looking into coref resolution lately, not sure if the change is necessary for this.

given that we now merged the rasa core code into the nlu one, I think the situation changed a bit on this one, as there is no reason for the http connection anymore, but rather it could make sense to use multiple interpreters and combine the same dialogue model with different nlu models. 

I think the general idea of adding the language information to the tracker is good @erohmensing is currently working on something that will allow us passing that information through from the input channel to the tracker (ofc, should also be possible to be set from somewhere else). 

In general, I think we need to be careful on how we introduce multi-language support, as it needs to be easy to use and we need to think through the whole development chain (how do you add languages, how is the training data structured, how does a multi-lang model look like, ...)

**Comment by alexissmirnov** [comment]
Completely agree on the need to be careful, and appreciate all the analysis thus far.

Given the recent refactoring of the code, would you say that splitting core and nlu into two different microservices is no longer advisable deployment strategy?

To me, multi-language is just one of the many use cases that would require passing contextual information to the tracker. If multi-language support is an important use-case, it would be good to answer those other questions.

**Comment by alexissmirnov** [comment]
@erohmensing any update on your work of passing data from the channel into the tracker, as @tmbo mentioned above?

**Comment by alexissmirnov** [comment]
As discussed with @amn41 this issue is still relevant.

I've put together a PR https://github.com/RasaHQ/rasa/pull/3681 that implements
- passing the tracker into the interpreter
- using the tracker in `RasaNLUHttpInterpreter` to lookup a slot and modify the domain name of the NLU endpoint
- extending the configuration to specify the slot name that RasaNLUHttpInterpreter should be looking at
- a unit test `test_processor.py::test_http_parsing_with_tracker` that sets the slot to 'en' to modify the NLU's endpoint

Please let me know your thoughts @erohmensing @tmbo 
Thanks!

**Comment by alexissmirnov** [comment]
Closing this issue since PR is merged.
